/*
 * DesktopApplication1View.java
 */

//GUI:
//formatted field to accept numbers for height
//two checkboxes for whether the user has back or heart problems
//output display updates automatically based on the input

//Code:
//updateDisplay:
//  gets height from height input box
//  converts height to integer
//  checks if height meets requirements
//  makes sure both checkboxes are unchecked
//  updates output message to reflect the information

//checkbox itemChanged listeners
//  call updateDisplay

//input box key typed listener:
//  creates a timer task that calls updateDisplay in one second
//  cancels previous task and starts over

package desktopapplication1;

import java.util.Timer;
import java.util.TimerTask;
import org.jdesktop.application.Action;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * The application's main frame.
 */
public class DesktopApplication1View extends FrameView {

    public DesktopApplication1View(SingleFrameApplication app) {
        super(app);
        initComponents();
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = DesktopApplication1.getApplication().getMainFrame();
            aboutBox = new DesktopApplication1AboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        DesktopApplication1.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        height = new javax.swing.JFormattedTextField();
        back = new javax.swing.JCheckBox();
        heart = new javax.swing.JCheckBox();
        display = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getResourceMap(DesktopApplication1View.class);
        title.setFont(resourceMap.getFont("title.font")); // NOI18N
        title.setForeground(resourceMap.getColor("title.foreground")); // NOI18N
        title.setText(resourceMap.getString("title.text")); // NOI18N
        title.setName("title"); // NOI18N

        heightLabel.setText(resourceMap.getString("heightLabel.text")); // NOI18N
        heightLabel.setName("heightLabel"); // NOI18N

        height.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        height.setText(resourceMap.getString("height.text")); // NOI18N
        height.setName("height"); // NOI18N
        height.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                heightKeyTyped(evt);
            }
        });

        back.setText(resourceMap.getString("back.text")); // NOI18N
        back.setToolTipText(resourceMap.getString("back.toolTipText")); // NOI18N
        back.setName("back"); // NOI18N
        back.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                backItemStateChanged(evt);
            }
        });

        heart.setText(resourceMap.getString("heart.text")); // NOI18N
        heart.setToolTipText(resourceMap.getString("heart.toolTipText")); // NOI18N
        heart.setName("heart"); // NOI18N
        heart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                heartItemStateChanged(evt);
            }
        });

        display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        display.setText(resourceMap.getString("display.text")); // NOI18N
        display.setName("display"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back)
                            .addComponent(heightLabel))
                        .addGap(25, 25, 25)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(height, 0, 0, Short.MAX_VALUE)
                            .addComponent(heart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(display, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(title, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightLabel)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(heart))
                .addGap(26, 26, 26)
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(desktopapplication1.DesktopApplication1.class).getContext().getActionMap(DesktopApplication1View.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setComponent(mainPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void updateDisplay() {
        int h = 0;
        try {
            h = Integer.parseInt(height.getText()); //convert text to int
        } catch (NumberFormatException e) {}

        //update message based on ride requirements
        if (h >= 122 && h <= 188 && !back.isSelected() && !heart.isSelected()) {
            display.setText("Welcome aboard; have fun on your ride!");
        } else {
            display.setText("Sorry, but for safety reasons, you are not permitted to go on this ride.");
        }
    }

    private void backItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_backItemStateChanged
        updateDisplay(); //update message when check changes
    }//GEN-LAST:event_backItemStateChanged

    private void heartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_heartItemStateChanged
        updateDisplay(); //update message when check changes
    }//GEN-LAST:event_heartItemStateChanged

    private Timer timer = new Timer(); //see below
    private TimerTask task; //see below
    private void heightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heightKeyTyped
        if (task != null) {
            task.cancel(); //cancel update because user is still typing
        }

        //create timer due for one second
        task = new TimerTask() {
            @Override
            public void run() {
                updateDisplay(); //update message
            }
        };

        timer.schedule(task, 500); //set timer for one second
    }//GEN-LAST:event_heightKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox back;
    private javax.swing.JLabel display;
    private javax.swing.JCheckBox heart;
    private javax.swing.JFormattedTextField height;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private JDialog aboutBox;
}
